[tool.poetry]
name = "sentential"
version = "0.0.1"
description = "because lambdas are good"
authors = ["Brendan Keane <btkeane@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.6.1"
boto3 = "^1.24.31"
python-on-whales = "^0.49.0"
pydantic = "^1.9.1"
Jinja2 = "^3.1.2"
PyYAML = "^6.0"
tabulate = "^0.8.10"

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"
python-semantic-release = "^7.29.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sntl = "sentential.sntl:main"

[tool.semantic_release]
version_variable = [
  "sentential/__init__.py:__version__",
  "pyproject.toml:version",
]
branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
