[tool.poetry]
name = "sentential"
version = "0.2.0"
description = "because lambdas are good"
authors = [
  "Brendan Keane <btkeane@gmail.com>",
  "Raymond Douglas <r@rymnd.org>"
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.6.1"
boto3 = "^1.24.31"
python-on-whales = ">=0.49,<0.51"
pydantic = "^1.9.1"
Jinja2 = "^3.1.2"
tabulate = "^0.8.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
python-semantic-release = "^7.31.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sntl = "sentential.sntl:main"

[tool.semantic_release]
version_variable = [
  "sentential/__init__.py:__version__",
  "pyproject.toml:version",
]
branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
